name 'puppet-hipchat'
version '0.0.1'
license 'Apache 2.0'
summary 'A Puppet report handler for sending notifications of failed runs to HipChat'
project_page 'https://github.com/jamtur01/puppet-hipchat'
